### ISSUE TITLE
DORA?

### ISSUE THREAD

**Issue by simenandre** [bjerkio/policies#9]
Hei 👋 

Jeg fant [Matteos (@mcollina) prinsipper](https://gist.github.com/mcollina/7da6fb84b8a4939ba2be99c003289513) tilfeldig på nett, og ble positivt overrasket over denne:

> Scrum and other Agile methodologies predicates the use of story points and time to assess how much work will fit in a sprint. Then, the team is benchmarked with these estimates. This incentives writing low quality software as bug fixes will be more story point to churn later on.
> 
> Continuous Deployment is the way. The best way to measure CD are DORA metrics:
> 
> - deployment frequency (DF)
> - lead time for changes (LT)
> - mean time to recovery (MTTR)
> - change failure rate (CFR)

Jeg har egentlig aldri sett noen beskrive så godt hva som er problemet med _story points_ eller estimater på generelt basis bedre. Ikke minst er jeg personlig veldig enig med alternativet. DORA-beregniner kommer orginalt fra [et forskningsprosjekt hos Google](https://www.devops-research.com). Så dette er ikke tatt fra lufta, men har et godt fundament. Det gjenspeiler mye av metodene og prosessene vi har i dag, og som vi kjemper mot å jobbe mer mot.

I januar 2020, ble det utformet et [interaktivt kart](https://www.devops-research.com/research.html) som jeg anbefaler å gå gjennom punkt for punkt for se nærmere.

Mitt forslag: Vi innlemmer dette i stillingsinstrukser. Vi skal jobbe mot å få våre kunder til å måle oss etter prinsippene i DORA.

**Comment by braaar** [comment]
> - Deployment Frequency—How often an organization successfully releases to production
> - Lead Time for Changes—The amount of time it takes a commit to get into production
> - Change Failure Rate—The percentage of deployments causing a failure in production
> - Time to Restore Service—How long it takes an organization to recover from a failure in production

Herfra: https://cloud.google.com/blog/products/devops-sre/using-the-four-keys-to-measure-your-devops-performance

**Comment by braaar** [comment]
Jeg er enig! Dette høres bra ut
